engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**index.js"
exclude_paths:
- "**/*test.js"
- ".eslintrc.js"
